'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Monografias.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Agregar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agregar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Agregar_Venta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agregar-Venta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- MySQL dump 10.13  Distrib 5.6.16, for Win32 (x86)
        '''--
        '''-- Host: localhost    Database: laminas
        '''-- ------------------------------------------------------
        '''-- Server version	5.6.16
        '''
        '''/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        '''/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        '''/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        '''/*!40101 SET NAMES utf8 */;
        '''/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
        '''/*!40103 SET TIME_ZONE=&apos;+00:00&apos; */;
        '''/*!40014 SET [resto de la cadena truncado]&quot;;.
        '''</summary>
        Public ReadOnly Property Estructura() As String
            Get
                Return ResourceManager.GetString("Estructura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Public ReadOnly Property Ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ImgDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property lupa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a # Example MySQL config file for small systems.
        '''#
        '''# This is for a system with little memory (&lt;= 64M) where MySQL is only used
        '''# from time to time and it&apos;s important that the mysqld daemon
        '''# doesn&apos;t use much resources.
        '''#
        '''# You can copy this file to
        '''# C:/xampp/mysql/bin/my.cnf to set global options,
        '''# mysql-data-dir/my.cnf to set server-specific options (in this
        '''# installation this directory is C:/xampp/mysql/data) or
        '''# ~/.my.cnf to set user-specific options.
        '''#
        '''# In this file, you can use all long  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Public ReadOnly Property my_mysql() As String
            Get
                Return ResourceManager.GetString("my_mysql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Recuperar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recuperar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a #
        '''# XAMPP settings
        '''#
        '''
        '''&lt;IfModule env_module&gt;
        '''    SetEnv MIBDIRS &quot;C:/xampp/php/extras/mibs&quot;
        '''    SetEnv MYSQL_HOME &quot;\\xampp\\mysql\\bin&quot;
        '''    SetEnv OPENSSL_CONF &quot;C:/xampp/apache/bin/openssl.cnf&quot;
        '''    SetEnv PHP_PEAR_SYSCONF_DIR &quot;\\xampp\\php&quot;
        '''    SetEnv PHPRC &quot;\\xampp\\php&quot;
        '''    SetEnv TMP &quot;\\xampp\\tmp&quot;
        '''&lt;/IfModule&gt;
        '''
        '''#
        '''# PHP-Module setup
        '''#
        '''LoadFile &quot;C:/xampp/php/php5ts.dll&quot;
        '''LoadFile &quot;C:/xampp/php/libpq.dll&quot;
        '''LoadModule php5_module &quot;C:/xampp/php/php5apache2_4.dll&quot;
        '''
        '''&lt;FilesMatch &quot;\.php$&quot;&gt;
        '''    Se [resto de la cadena truncado]&quot;;.
        '''</summary>
        Public ReadOnly Property Xampp_Security() As String
            Get
                Return ResourceManager.GetString("Xampp_Security", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a #
        '''# XAMPP settings
        '''#
        '''
        '''&lt;IfModule env_module&gt;
        '''    SetEnv MIBDIRS &quot;C:/xampp/php/extras/mibs&quot;
        '''    SetEnv MYSQL_HOME &quot;\\xampp\\mysql\\bin&quot;
        '''    SetEnv OPENSSL_CONF &quot;C:/xampp/apache/bin/openssl.cnf&quot;
        '''    SetEnv PHP_PEAR_SYSCONF_DIR &quot;\\xampp\\php&quot;
        '''    SetEnv PHPRC &quot;\\xampp\\php&quot;
        '''    SetEnv TMP &quot;\\xampp\\tmp&quot;
        '''&lt;/IfModule&gt;
        '''
        '''#
        '''# PHP-Module setup
        '''#
        '''LoadFile &quot;C:/xampp/php/php5ts.dll&quot;
        '''LoadFile &quot;C:/xampp/php/libpq.dll&quot;
        '''LoadModule php5_module &quot;C:/xampp/php/php5apache2_4.dll&quot;
        '''
        '''&lt;FilesMatch &quot;\.php$&quot;&gt;
        '''    Se [resto de la cadena truncado]&quot;;.
        '''</summary>
        Public ReadOnly Property Xampp_Security_NM() As String
            Get
                Return ResourceManager.GetString("Xampp_Security_NM", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
